version: '3.9'
services:
  levelup-express-backend-dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: levelup-express-backend-dev
    container_name: levelup-express-backend-dev
    restart: unless-stopped
    ports:
      - '3000:3000'
